version: '3.8'

services:
  torrentmonitor:
    image: tormon:latest
    build:
      context: .
      args:
        # Передаем UID и GID текущего пользователя хоста
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: torrentmonitor
    restart: unless-stopped
    ports:
      - "7060:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - media
    volumes:
      - .:/var/www/html
      - torrmon_torrentfiles:/var/www/html/torrents
      - torrmon_db:/var/www/html/db

volumes:
  torrmon_torrentfiles:
    name: torrmon_torrentfiles
  torrmon_db:
    name: torrmon_db

networks:
  media:
    external: true
