version: '3.8'

services:
  torrentmonitor:
    image: tormon:latest
    build:
      context: .
      args:
        # Передаем UID и GID текущего пользователя хоста
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: torrentmonitor
    restart: unless-stopped
    ports:
      - "7060:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - media
    volumes:
      - .:/var/www/html
      - ./torrents:/var/www/html/torrents
      - ./db:/var/www/html/db

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    external: true
